steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']
  # Run SonarCloud analysis
  - name: 'us-docker.pkg.dev/xer-demo-devops-prd/sonar-scanner/sonar-scanner:latest'
    entrypoint: 'sonar-scanner'
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.projectKey=react-demo-sq'
      - '-Dsonar.organization=danielssperez'
      - '-Dsonar.exclusions=Dockerfile,**/*.html,**/*.json,**/*.yaml'
      - '-Dsonar.sources=.'
      - '-Dsonar.tests=src/tests'
    env:
      - SONAR_TOKEN=b47692e9f54b35339ce70aa592a3f5ba1bbe7735
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install jq -y
        # Realizar la solicitud a la API de SonarCloud
        response=$(curl -s -u 8624735de16766a8f22d48c99847cf2f1e99590b: https://sonarcloud.io/api/qualitygates/project_status?projectKey=react-demo-sq)
        # Extraer el estado del Quality Gate del JSON de respuesta
        status=$(echo $response | jq -r '.projectStatus.status')
        # Verifica el estado del Quality Gate
        if [ "$status" = "ERROR" ]; then
          echo "Quality Gate FAILED"
          exit 1
        elif [ "$status" = "OK" ]; then
          echo "Quality Gate PASSED"
          exit 0
        fi
artifacts:
  objects:
    location: 'gs://gcp-csr-demo-devops-gcr-logs/reportes'
    paths: ['index.html']


logsBucket: gcp-csr-demo-devops-gcr-logs
