steps:
  # Paso 1: Instalar dependencias
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['ci']

  # Paso 2: Ejecutar pruebas con cobertura
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['test']

  # Run SonarCloud analysis
  - name: 'us-docker.pkg.dev/xer-demo-devops-prd/sonar-scanner/sonar-scanner:latest'
    entrypoint: 'sonar-scanner'
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.projectKey=react-demo-sq'
      - '-Dsonar.organization=danielssperez'
      - '-Dsonar.exclusions=Dockerfile,**/*.html,**/*.json,**/*.yaml'
      - '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
      - '-Dsonar.sources=src'
      - '-Dsonar.tests=tests'
    env:
      - SONAR_TOKEN=b47692e9f54b35339ce70aa592a3f5ba1bbe7735
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install jq -y
        # Realizar la solicitud a la API de SonarCloud
        response=$(curl -s -u 8624735de16766a8f22d48c99847cf2f1e99590b: https://sonarcloud.io/api/qualitygates/project_status?projectKey=react-demo-sq)
        # Extraer el estado del Quality Gate del JSON de respuesta
        status=$(echo $response | jq -r '.projectStatus.status')
        # Verifica el estado del Quality Gate
        if [ "$status" = "ERROR" ]; then
          echo "Quality Gate FAILED"
          exit 1
        elif [ "$status" = "OK" ]; then
          echo "Quality Gate PASSED"
          exit 0
        fi


logsBucket: gcp-csr-demo-devops-gcr-logs
